"""Collecting preferences with Google Forms instead of the app.

1. apps_script() writes a Google Apps Script that creates the form in your
   Google Drive (paste it at script.google.com and press Run; see README).
   With a roster, TAs pick their name from a list that shows their hours.
2. TAs fill in the form. Download the responses as a CSV.
3. Use that CSV as the preferences file: read_participants() recognises it
   (is_export) and converts it (to_preferences). If a TA answered more than
   once, their latest answer counts.
"""
from __future__ import annotations

import json
import math
import re

import pandas as pd

from .models import Schedule, fmt_time, name_key

HOURS_SUFFIX = re.compile(r"\s*\(\d+ h/week\)$")  # "Ada (4 h/week)" -> "Ada"


def is_export(df: pd.DataFrame) -> bool:
    cols = [c.lower() for c in df.columns]
    return "timestamp" in cols and any(c.startswith("choice") for c in cols)


def to_preferences(df: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    """Google Forms export -> preferences table (name, [hours], unavailable, submitted, pref...)."""
    lower = {c.lower(): c for c in df.columns}
    if "name" not in lower:
        raise ValueError("the Google Forms export needs a 'Name' question")
    hours_col = next((c for c in df.columns if c.lower().startswith("hours")), None)
    unavail_cols = [c for c in df.columns if c.lower().startswith("unavailable")]
    choice_cols = [c for c in df.columns if c.lower().startswith("choice")]  # in question order

    latest: dict[str, dict] = {}
    warnings = []
    for _, row in df.iterrows():
        name = HOURS_SUFFIX.sub("", row[lower["name"]]).strip()
        if not name:
            continue
        if name_key(name) in latest:
            warnings.append(f"{name} answered the form more than once; using their latest answer")
        prefs = []
        for col in choice_cols:
            label = row[col].split("-")[0].strip()  # "Mon 12:00-13:00" -> "Mon 12:00"
            if label in prefs:
                warnings.append(f"{name} picked {label} for more than one choice; only the first counts")
            elif label:
                prefs.append(label)
        latest[name_key(name)] = {
            "name": name,
            **({"hours": row[hours_col]} if hours_col else {}),
            "unavailable": "; ".join(row[c] for c in unavail_cols if row[c]),
            "submitted": row[lower["timestamp"]],
            "prefs": prefs,
        }

    width = max((len(r["prefs"]) for r in latest.values()), default=0)
    rows = [{**{k: v for k, v in r.items() if k != "prefs"},
             **{f"pref{i + 1}": p for i, p in enumerate(r["prefs"])}} for r in latest.values()]
    columns = ["name", *(["hours"] if hours_col else []), "unavailable", "submitted",
               *(f"pref{i + 1}" for i in range(width))]
    return pd.DataFrame(rows, columns=columns).fillna("").astype(str), warnings


# what TAs may type as busy times (the same entries parse_unavailable reads)
_ENTRY = r"[A-Za-z]+(\s+\d{1,2}(:\d{2})?(\s*-\s*\d{1,2}(:\d{2})?)?)?"
BUSY_PATTERN = rf"^\s*{_ENTRY}(\s*[;,]\s*{_ENTRY})*\s*$"

_SCRIPT = """/**
 * Creates the MLC preference form in your Google Drive.
 * Generated by mlc_scheduler for this term's schedule{roster_note}.
 *
 *  1. Open https://script.google.com and click "New project".
 *  2. Replace the code there with this whole file, save, and click Run.
 *  3. Allow the permissions it asks for (it only creates this one form).
 *  4. The execution log shows the link to send to TAs and the link to
 *     edit the form. Responses: in the form's Responses tab, use the menu
 *     to download them as a CSV, then give that CSV to mlc_scheduler.
 */
const TITLE = {title};
const NAMES = {names};
const DAYS = {days};
const SLOTS = {slots};
const CHOICES = {choices};
const REQUIRED_CHOICES = {required};
const BUSY_PATTERN = {pattern};

function createForm() {{
  const form = FormApp.create(TITLE).setDescription(
    "Rank the MLC slots you would like to work. You don't need to be fast: everyone's " +
    "lists are combined at the end to give each TA slots as high in their ranking as " +
    "possible. Every slot lasts one hour. If you submit again, your latest answer counts.");

  if (NAMES.length > 0) {{
    form.addListItem().setTitle("Name").setRequired(true).setChoiceValues(NAMES)
      .setHelpText("Your hours per week are shown next to your name. Not on the list? Contact the MLC.");
  }} else {{
    form.addTextItem().setTitle("Name").setRequired(true)
      .setHelpText("Use the same name if you submit again.");
    form.addTextItem().setTitle("Hours per week").setRequired(true)
      .setValidation(FormApp.createTextValidation().requireWholeNumber().build());
  }}

  form.addCheckboxItem().setTitle("Unavailable days").setChoiceValues(DAYS)
    .setHelpText("Days you can't work at all.");
  form.addTextItem().setTitle("Unavailable times")
    .setHelpText("Other times you can't work, e.g. your classes: Tue 13:00-14:30; Thu 13:00-14:30. " +
                 "A time range rules out every slot that overlaps it.")
    .setValidation(FormApp.createTextValidation().requireTextMatchesPattern(BUSY_PATTERN)
      .setHelpText("Write entries like Tue 13:00-14:30, separated by ;").build());

  form.addPageBreakItem().setTitle("Your ranked slots").setHelpText(
    "Choice 1 is your favourite. Rank at least {factor} slots for every hour you work " +
    "(more can only help you), and don't pick slots that clash with your unavailable times.");
  for (let i = 1; i <= CHOICES; i++) {{
    form.addListItem().setTitle("Choice " + i + (i === 1 ? " (favourite)" : ""))
      .setChoiceValues(SLOTS).setRequired(i <= REQUIRED_CHOICES);
  }}

  Logger.log("Send this link to TAs: " + form.getPublishedUrl());
  Logger.log("Edit the form and see responses: " + form.getEditUrl());
}}
"""


def apps_script(
    schedule: Schedule,
    roster: list[dict] | None = None,
    min_list_factor: float = 2.0,
    choices: int | None = None,
    title: str = "MLC preference form",
) -> str:
    order = {d: i for i, d in enumerate(schedule.days)}
    slots = sorted(schedule.slots, key=lambda s: (order[s.day], s.start))
    hours = [r["hours"] for r in roster or []]
    if choices is None:
        choices = math.ceil(min_list_factor * max(hours)) + 4 if hours else 20
    choices = min(choices, len(slots))
    required = min(choices, max(1, math.ceil(min_list_factor * min(hours)) if hours else 1))
    return _SCRIPT.format(
        roster_note=" and roster" if roster else "",
        title=json.dumps(title),
        names=json.dumps([f"{r['name']} ({r['hours']} h/week)" for r in roster or []], indent=2),
        days=json.dumps(schedule.days),
        slots=json.dumps([f"{s.label}-{fmt_time(s.end)}" for s in slots], indent=2),
        choices=choices,
        required=required,
        pattern=json.dumps(BUSY_PATTERN),
        factor=f"{min_list_factor:g}",
    )
